/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'en') | ('ru' | 'en')[];
  globals: {
    header: Header;
    homePage: HomePage;
    footer: Footer;
    brand: Brand;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    homePage: HomePageSelect<false> | HomePageSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    brand: BrandSelect<false> | BrandSelect<true>;
  };
  locale: 'ru' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Краткое описание изображения для доступности и поисковой оптимизации.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Автоматически созданные результаты для поиска в админке. Откройте «Поиск» в боковом меню и используйте строку поиска над списком — она ищет по заголовку. Записи обновляются при сохранении глобальных настроек и пользователей; после обновления CMS выполняется полная переиндексация.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  globalSlug?: string | null;
  globalFieldKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  globalSlug?: T;
  globalFieldKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  siteName?: string | null;
  /**
   * Основное меню шапки сайта. Добавляйте пункты с названием и ссылкой; иконку можно показывать в меню или только на мобильных. Подпункты превращают пункт в мега-меню — URL верхнего уровня тогда необязателен.
   */
  navigation?:
    | {
        /**
         * SVG отображается встроенным на сайте; PNG/WebP — как изображение.
         */
        icon?: (number | null) | Media;
        /**
         * Если включено, иконка показывается только в мобильном меню, не в десктопной навигации.
         */
        mobileMenuOnly?: boolean | null;
        label: string;
        /**
         * Необязательно, если добавлено подменю.
         */
        url?: string | null;
        openInNewTab?: boolean | null;
        /**
         * Если добавлены подпункты, пункт отображается как мега-меню.
         */
        subItems?:
          | {
              /**
               * SVG отображается встроенным на сайте; PNG/WebP — как изображение.
               */
              icon?: (number | null) | Media;
              label: string;
              url: string;
              openInNewTab?: boolean | null;
              /**
               * Можно использовать &nbsp; для неразрывного пробела.
               */
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Список ссылок с подписями и иконками (tel:, mailto:, https: и т.д.).
   */
  phones?:
    | {
        number: string;
        /**
         * Необязательно. Например: tel:+74951234567, mailto:info@example.com или https://…
         */
        url?: string | null;
        openInNewTab?: boolean | null;
        iconType?: ('hugeicons' | 'custom' | 'none') | null;
        /**
         * Выберите иконку из бесплатного набора Hugeicons. Используйте поиск по названию.
         */
        hugeiconsName?: string | null;
        /**
         * Загрузите SVG или изображение для отображения рядом с подписью.
         */
        customIcon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Список ссылок с подписями и иконками (tel:, mailto:, https: и т.д.).
   */
  rightLinks?:
    | {
        number: string;
        /**
         * Необязательно. Например: tel:+74951234567, mailto:info@example.com или https://…
         */
        url?: string | null;
        openInNewTab?: boolean | null;
        iconType?: ('hugeicons' | 'custom' | 'none') | null;
        /**
         * Выберите иконку из бесплатного набора Hugeicons. Используйте поиск по названию.
         */
        hugeiconsName?: string | null;
        /**
         * Загрузите SVG или изображение для отображения рядом с подписью.
         */
        customIcon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  /**
   * Резервный заголовок для метаданных и H1, если блок Hero не задан.
   */
  title?: string | null;
  /**
   * Заголовок для поисковых систем и вкладки браузера.
   */
  metaTitle?: string | null;
  /**
   * Краткое описание страницы для поисковых систем.
   */
  metaDescription?: string | null;
  /**
   * Изображение для предпросмотра в соцсетях. Рекомендуемый размер: 1200×630 px.
   */
  ogImage?: (number | null) | Media;
  /**
   * Если включено, страница не будет индексироваться (noindex).
   */
  noIndex?: boolean | null;
  blocks?:
    | (
        | {
            /**
             * Текст заголовка Hero-блока на сайте.
             */
            headlineSection: {
              /**
               * Можно использовать &nbsp; для неразрывного пробела между словами.
               */
              headline: string;
            };
            /**
             * Необязательное изображение справа от текста на сайте.
             */
            imageSection?: {
              image?: (number | null) | Media;
            };
            /**
             * Необязательные бейджи под заголовком (магазины приложений, сервисы и т.п.).
             */
            subscriptionsSection?: {
              badges?:
                | {
                    /**
                     * Выберите иконку из библиотеки бренда (Настройки → Бренд → Иконки).
                     */
                    image?: (number | null) | Media;
                    label?: string | null;
                    /**
                     * Относительный (/about) или абсолютный (https://…) URL.
                     */
                    url?: string | null;
                    /**
                     * Выберите фон из библиотеки бренда (Настройки → Бренд → Фон).
                     */
                    backgroundColor?: string | null;
                    /**
                     * Выберите цвет из библиотеки бренда (Настройки → Бренд → Цвет).
                     */
                    textColor?: string | null;
                    openInNewTab?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
            };
            /**
             * Необязательные кнопки призыва к действию под бейджами. Максимум 2.
             */
            buttonsSection?: {
              buttons?:
                | {
                    label?: string | null;
                    /**
                     * Относительный (/about) или абсолютный (https://…) URL.
                     */
                    url?: string | null;
                    variant?: ('primary' | 'secondary' | 'outline' | 'white' | 'green') | null;
                    openInNewTab?: boolean | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            text: string;
            /**
             * Вертикальный отступ над заголовком на десктопе (px). По умолчанию — 24 px.
             */
            spacingTop?: number | null;
            /**
             * Вертикальный отступ под заголовком на десктопе (px). По умолчанию — 24 px.
             */
            spacingBottom?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headingH2';
          }
        | {
            icon?: (number | null) | Media;
            title: string;
            /**
             * Отображает бейдж «beta» рядом с заголовком на сайте.
             */
            showBetaBadge?: boolean | null;
            /**
             * Можно использовать &nbsp; для неразрывного пробела.
             */
            description?: string | null;
            /**
             * Картинка блока и её расположение относительно текста.
             */
            imageSection?: {
              image?: (number | null) | Media;
              /**
               * На сайте применяется скругление rounded-md у картинки.
               */
              roundedImage?: boolean | null;
              position?: ('right' | 'left') | null;
            };
            /**
             * Необязательная кнопка под описанием.
             */
            buttonSection?: {
              label?: string | null;
              /**
               * Относительный (/about) или абсолютный (https://…) URL.
               */
              url?: string | null;
              variant?: ('primary' | 'secondary' | 'outline' | 'white' | 'green') | null;
              openInNewTab?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureSection';
          }
        | {
            /**
             * Количество карточек в ряд на широких экранах.
             */
            columns?: ('1' | '2' | '3' | '4') | null;
            items?:
              | {
                  title: string;
                  /**
                   * Можно использовать &nbsp; для неразрывного пробела.
                   */
                  description?: string | null;
                  /**
                   * Горизонтальное выравнивание текста и вертикальное положение блока контента в карточке.
                   */
                  content?: {
                    /**
                     * Горизонтальное выравнивание заголовка, описания и кнопки.
                     */
                    align?: ('left' | 'center') | null;
                    /**
                     * Вертикальное положение блока контента внутри карточки.
                     */
                    position?: ('top' | 'center') | null;
                  };
                  /**
                   * Медиа карточки: иконка над заголовком или картинка слева, справа, сверху или под контентом.
                   */
                  img?: {
                    /**
                     * Без картинки — только текст. Иконка — медиа над заголовком. Картинка — расположение задаётся полем ниже.
                     */
                    mediaType?: ('none' | 'icon' | 'image') | null;
                    /**
                     * Иконка или картинка в зависимости от выбранного типа медиа.
                     */
                    image?: (number | null) | Media;
                    /**
                     * Где показывать картинку относительно текста: слева/справа (на планшете «слева» — сверху, «справа» — снизу) или сверху/снизу на всех экранах.
                     */
                    position?: ('left' | 'right' | 'top' | 'bottom') | null;
                    /**
                     * Только для расположения «Слева» или «Справа»: вертикальное выравнивание картинки внутри колонки.
                     */
                    imageAlign?: ('top' | 'bottom' | 'stretch') | null;
                    /**
                     * На сайте применяется скругление rounded-md у картинки.
                     */
                    rounded?: boolean | null;
                  };
                  /**
                   * Ссылка в карточке: отдельная кнопка или клик по всей карточке (нужен URL).
                   */
                  btn?: {
                    /**
                     * «Без кнопки» — карточка без ссылки. «Кнопка в карточке» — ссылка в виде кнопки. «Вся карточка» — переход по клику на карточку.
                     */
                    linkMode?: ('none' | 'button' | 'card') | null;
                    label?: string | null;
                    /**
                     * Относительный (/about) или абсолютный (https://…) URL.
                     */
                    url?: string | null;
                    variant?: ('primary' | 'secondary' | 'outline' | 'white' | 'green') | null;
                    openInNewTab?: boolean | null;
                  };
                  /**
                   * Базовый — стандартный фон сайта. Брендовый — пресет из «Настройки → Бренд → Фон». Свой — произвольный цвет.
                   */
                  backgroundMode?: ('default' | 'brand' | 'custom') | null;
                  /**
                   * Пресет из библиотеки бренда (Настройки → Бренд → Фон).
                   */
                  brandBackgroundId?: string | null;
                  /**
                   * Произвольный цвет фона карточки в формате #RRGGBB.
                   */
                  backgroundColor?: string | null;
                  /**
                   * На сайте карточка занимает указанное число колонок сетки (col-span). На мобильных устройствах карточки всегда на всю ширину.
                   */
                  gridSpan?: ('1' | '2' | 'full') | null;
                  /**
                   * Внутренние отступы карточки. По умолчанию включены со всех сторон (p-6 / lg:p-12).
                   */
                  padding?: {
                    paddingLeft?: boolean | null;
                    paddingTop?: boolean | null;
                    paddingRight?: boolean | null;
                    paddingBottom?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardsGrid';
          }
      )[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Например: © 2026 IVA360. Все права защищены.
   */
  copyright?: string | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'vk' | 'telegram' | 'youtube' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Библиотека логотипов, иконок, фонов и цветов для выбора в других разделах CMS.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand".
 */
export interface Brand {
  id: number;
  /**
   * Логотипы из этого списка доступны в полях выбора логотипа бренда.
   */
  logos?:
    | {
        name: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Иконки из этого списка доступны в полях выбора иконки бренда.
   */
  icons?:
    | {
        name: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Фоны из этого списка доступны в полях выбора фона бренда.
   */
  backgrounds?:
    | {
        name: string;
        color: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Цвета из этого списка доступны в полях выбора цвета бренда.
   */
  colors?:
    | {
        name: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  siteName?: T;
  navigation?:
    | T
    | {
        icon?: T;
        mobileMenuOnly?: T;
        label?: T;
        url?: T;
        openInNewTab?: T;
        subItems?:
          | T
          | {
              icon?: T;
              label?: T;
              url?: T;
              openInNewTab?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  phones?:
    | T
    | {
        number?: T;
        url?: T;
        openInNewTab?: T;
        iconType?: T;
        hugeiconsName?: T;
        customIcon?: T;
        id?: T;
      };
  rightLinks?:
    | T
    | {
        number?: T;
        url?: T;
        openInNewTab?: T;
        iconType?: T;
        hugeiconsName?: T;
        customIcon?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  title?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  noIndex?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              headlineSection?:
                | T
                | {
                    headline?: T;
                  };
              imageSection?:
                | T
                | {
                    image?: T;
                  };
              subscriptionsSection?:
                | T
                | {
                    badges?:
                      | T
                      | {
                          image?: T;
                          label?: T;
                          url?: T;
                          backgroundColor?: T;
                          textColor?: T;
                          openInNewTab?: T;
                          id?: T;
                        };
                  };
              buttonsSection?:
                | T
                | {
                    buttons?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          variant?: T;
                          openInNewTab?: T;
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        headingH2?:
          | T
          | {
              text?: T;
              spacingTop?: T;
              spacingBottom?: T;
              id?: T;
              blockName?: T;
            };
        featureSection?:
          | T
          | {
              icon?: T;
              title?: T;
              showBetaBadge?: T;
              description?: T;
              imageSection?:
                | T
                | {
                    image?: T;
                    roundedImage?: T;
                    position?: T;
                  };
              buttonSection?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    openInNewTab?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cardsGrid?:
          | T
          | {
              columns?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    content?:
                      | T
                      | {
                          align?: T;
                          position?: T;
                        };
                    img?:
                      | T
                      | {
                          mediaType?: T;
                          image?: T;
                          position?: T;
                          imageAlign?: T;
                          rounded?: T;
                        };
                    btn?:
                      | T
                      | {
                          linkMode?: T;
                          label?: T;
                          url?: T;
                          variant?: T;
                          openInNewTab?: T;
                        };
                    backgroundMode?: T;
                    brandBackgroundId?: T;
                    backgroundColor?: T;
                    gridSpan?: T;
                    padding?:
                      | T
                      | {
                          paddingLeft?: T;
                          paddingTop?: T;
                          paddingRight?: T;
                          paddingBottom?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  copyright?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand_select".
 */
export interface BrandSelect<T extends boolean = true> {
  logos?:
    | T
    | {
        name?: T;
        image?: T;
        id?: T;
      };
  icons?:
    | T
    | {
        name?: T;
        image?: T;
        id?: T;
      };
  backgrounds?:
    | T
    | {
        name?: T;
        color?: T;
        id?: T;
      };
  colors?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}